config/routes.rb
Refinery::Application.routes.draw do

  match '/discounts',  :controller => 'discounts', :action => 'fulfill_index'
  match '/fulfillment_print/:id'=> "coupons#fulfillment_print", :as => :coupon_fulfillment_print
  match '/fulfillment_option/:id'=> "coupons#fulfillment_option", :as => :coupon_fulfillment_option
  match '/discounts/search', :controller => 'discounts', :action => 'search'
  match '/discounts/simple_search', :controller => 'discounts', :action => 'simple_search'
  match '/discounts/thanks_submit', :controller => 'discounts', :action => 'thanks_submit'
  match '/fulfillment/:id'=> "coupons#fulfillment", :as => :coupon_fulfillment
  match '/fulfillment_print/:id'=> "coupons#fulfillment_print", :as => :coupon_fulfillment_print
  match '/fulfillment_option/:id'=> "coupons#fulfillment_option", :as => :coupon_fulfillment_option
  match '/printable_discount/:id' => "coupons#prescription_discount", :as => :coupon_printable_discount
  match '/printable_discount_1/:id' => "coupons#prescription_discount_1", :as => :coupon_printable_discount_1
  match '/printable_discount_2/:id' => "coupons#prescription_discount_2", :as => :coupon_printable_discount_2
  match '/printable_discount_3/:id' => "coupons#prescription_discount_3", :as => :coupon_printable_discount_3
  match '/printable_discount_4/:id' => "coupons#prescription_discount_4", :as => :coupon_printable_discount_4
  match '/printable_discount_5/:id' => "coupons#prescription_discount_5", :as => :coupon_printable_discount_5
  match '/printable_discount_6/:id' => "coupons#prescription_discount_6", :as => :coupon_printable_discount_6
  match '/printable_discount', :controller => 'discounts', :action => 'index'  
  match '/PRESCRIPTION_DISCOUNT', :controller => 'discounts', :action => 'index'
  match '/PRESCRIPTION_DISCOUNT/:coupon', :controller => 'coupons', :action => 'prescription_discount'
  scope "fulfill" do
    match '/printable_discount', :controller => 'discounts', :action => 'fulfill_index', :as => :fulfill_discounts
    match '/discounts', :controller => 'discounts', :action => 'fulfill_index', :as => :fulfill_discounts
  end
  mount Refinery::Core::Engine, :at => '/'

end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
  
  validates :name, :presence => true, :uniqueness => true, :length => { :maximum => 255 }
  validates :savings, :presence => true
  has_many :common_diseases_and_meds, :primary_key => :name, :foreign_key => :drug
  has_many :common_drug_and_generics, :primary_key => :name, :foreign_key => :drug
  has_many :common_drug_misspellings, :primary_key => :name, :foreign_key => :drug
  has_many :ratings, :primary_key => :id, :foreign_key => :coupon_id
  has_one  :coupon_content,:primary_key => :name,:foreign_key => :name
  
  define_index do
    # fields
    indexes :name , :as => :coupons_name, :facet => true
    indexes :savings , :as => :savings, :facet => true
    indexes :ailment , :as => :ailment, :facet => true
    indexes :thumb_loc , :as => :thumb_loc, :facet => true
    indexes :page_loc , :as => :page_loc, :facet => true
    indexes :new_savings  , :as => :new_savings, :facet => true
    indexes :priority , :as => :priority_coupon, :facet => true
    indexes :browse , :as => :browse_coupon, :facet => true
    indexes common_diseases_and_meds.diseases, :as => :cdam
    indexes common_drug_and_generics.generic, :as => :cdag
    indexes common_drug_misspellings.query, :as => :cdm
    
    has :id
    has :name
    has :priority
    has :browse
    has :created_at, :updated_at
    
    set_property :delta => :delayed
  end
  before_save :check_savings

  def check_savings
   if self.savings.scan("%").blank? && self.savings.scan("$").blank? 
    self.savings = !self.savings.scan(".").blank? ? (self.savings.to_f * 100).round(0).to_s + "%" : (self.savings + "%")
   end
  end
  
  def to_param
    "#{id}-#{self.name.parameterize}"
  end
end

app/controllers/coupons_controller.rb
require 'csv'
class CouponsController < ApplicationController
  before_filter :require_user,:only=>[:index,:show,:new,:edit,:destroy,:update,:create,:userinfos]
  before_filter :call_api_flag , :only => [:prescription_discount_1,:prescription_discount_2,:prescription_discount_3,:prescription_discount_4,:prescription_discount_5,:prescription_discount_6,:prescription_discount, :print_prescription_discount, :spanish_prescription_discount]
  before_filter :set_source , :only => [:print_prescription_discount]
  before_filter :set_goog_old_flow , :only => [:prescription_discount]
  before_filter :before_prescription_discount, :only => [:prescription_discount_1,:prescription_discount_2,:prescription_discount_3,:prescription_discount_4,:prescription_discount_5,:prescription_discount_6,:prescription_discount, :email_prescription_discount, :sms_prescription_discount, :print_prescription_discount, :spanish_prescription_discount]
   layout "admin"

  def search
   name = params[:search] if params[:search]
   @per_page = 100
   session[:name] = name if !params[:page]
   @name = session[:name]
   @coupons = Coupon.paginate(:conditions => ['name LIKE ? ', '%'+@name+'%'],:per_page => @per_page, :page => params[:page])
   render :template=>'/coupons/index'
  end

  def ratings
    if cookies[:hlprx_ratings].blank?
     if params[:rating_sites]
      session[:ratings_name] = params[:rating_sites][:name]
       @rating_site = RatingSite.new(params[:rating_sites])
       respond_to do |format|
         if @rating_site.save
         cookies[:hlprx_ratings] = {:value =>"Rating added by #{request.env['REMOTE_ADDR']} ", :expires => Time.now + 90.days} if cookies[:hlprx_ratings].blank?
           session[:ratings_name] = ""
           @message = "Your ratings and review for the site has been successfully submitted."
           format.html {render :layout => false, :message => @message }
         else
           @err_msg = @rating_site.errors.full_messages
           format.html {render :layout => false, :message => "", :err_msg => @err_msg}
           format.xml  { render :xml => @rating_site.errors, :status => :unprocessable_entity }
         end
       end
     elsif params[:rating_coupons]
       @rating_coupon = RatingCoupon.new(params[:rating_coupons])
       respond_to do |format|
         if @rating_coupon.save
           rating_coupons = RatingCoupon.find(:all, :conditions => {:coupon_id => @rating_coupon.coupon_id})
             total_rate = 0
             rating_coupons.each do |r|
               total_rate = total_rate + r.rate
             end
             if rating_coupons.count == 0 then cnt = 1 else cnt = rating_coupons.count end
             avg = total_rate/cnt.to_f
             Coupon.update_all({:avg_rating => avg}, {:id => @rating_coupon.coupon_id})
             cookies[:hlprx_ratings] = {:value =>"Rating added by #{request.env['REMOTE_ADDR']} ", :expires => Time.now + 90.days} if cookies[:hlprx_ratings].blank?
           @message = "Your ratings and review for the coupon has been successfully submitted."
           format.html {render :layout => false, :message => @message }
         else
           @message = @rating_coupon.errors.full_messages
           format.html {render :layout => false, :message => @message}
           format.xml  { render :xml => @rating_coupon.errors, :status => :unprocessable_entity }
         end
       end
     else
       respond_to do |format|
         format.html {render :layout => false}
       end
     end
    else
      respond_to do |format|
         format.html {render :layout => false}
       end
   end
  end
  def pdf_download
        send_file("#{Rails.root}/public/monograph_pdf/#{params[:file]}")
  end

  def index
    @per_page = 100
    @search = params[:search] if params[:search]
    if params[:search]
      if params[:search][:top_coupon]
        @coupons = Coupon.paginate(:conditions=> ['top_coupon = ?', params[:search][:top_coupon]],:per_page => @per_page, :page => params[:page])
      end
    else
        @coupons = Coupon.paginate(:per_page => @per_page, :page => params[:page])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @coupons }
    end
  end

   def show
    @coupon = Coupon.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @coupon }
    end
  end

   def new
    @coupon = Coupon.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @coupon }
    end
  end

   def edit
    @coupon = Coupon.find(params[:id])
  end

   def create
    @coupon = Coupon.new(params[:coupon])

    respond_to do |format|
      if @coupon.save
        flash[:notice] = 'Coupon was successfully created.'
        format.html { redirect_to(coupons_url) }
        format.xml  { render :xml => @coupon, :status => :created, :location => @state }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @coupon.errors, :status => :unprocessable_entity }
      end
    end
  end

   def update
    @coupon = Coupon.find(params[:id])

    respond_to do |format|
      if @coupon.update_attributes(params[:coupon])
        flash[:notice] = 'Coupon was successfully updated.'
        format.html { redirect_to(coupons_url) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @coupon.errors, :status => :unprocessable_entity }
      end
    end
  end

   def destroy
    @coupon = Coupon.find(params[:id])
    @coupon.destroy

    respond_to do |format|
      format.html { redirect_to(coupons_url) }
      format.xml  { head :ok }
    end
  end

  def send_coupon_email
    email = params[:email]
    coupon = Coupon.find_by_id(params[:coupon_id])
    medicine = coupon.name if coupon
    discount = coupon.savings.strip.gsub('%','') if coupon
    subsource = cookies[:hlprx_utm_subsource]
    creative = cookies[:hlprx_utm_creative]
    source_tracking3 = cookies[:hlprx_utm_source]
    source,sourcekey = generate_source(source_tracking3)
    matchtype    = session[:matchtype]
    adid         = session[:adid]
    term         = session[:utm_term]
    browser      = get_browser(request.env['HTTP_USER_AGENT'].downcase)
    os           = get_operating_system(request.env['HTTP_USER_AGENT'].downcase)
    device       = get_device(request.env['HTTP_USER_AGENT'].downcase)
    searchstring = session[:searchstring]
    if !coupon.blank?
      options = {:coupon=>coupon.name,:savings=>coupon.savings.to_f,:searchstring=>searchstring,:browser=>browser,:os=>os,:device=>device,:ip=>request.env['REMOTE_ADDR'],:matchtype => matchtype,:adid => adid,:matchterm => term,:send_coupon_email => 'true', :source=>source,:sourcekey=>sourcekey, :subsource => subsource, :creative => creative, :prescription=> medicine, :email => email, :discount => discount}
      response     = get_coupon_value(options)
      @api_response = get_contact(response["Contacts"]) if response && response["Contacts"]
      cookies[:hlprx_prospect_id] = {:value => @api_response["ProspectId"], :expires => Time.now + 30.days} if @api_response && @api_response["ProspectId"]
      if !params[:userinfo_id].blank?
        Userinfo.update_all({:searchstring=>searchstring,:network=>cookies[:hlprx_network],:browser=>browser,:os=>os,:device=>device,:matchtype => matchtype,:adid => adid,:matchterm => term,:email => params[:email] ,:api_response=>(!response["Errors"].blank?||response["HasWarnings"]) ? (response["Errors"].join(',')+response["Warnings"].join(',')) : nil , :api_success =>response["Success"],:prospectid => cookies[:hlprx_prospect_id],:bin=>@api_response["BIN"],:pcn=>@api_response["PCN"],:member_number=>@api_response["MemberNumber"] },{:id => params[:userinfo_id]})
	##  update member number, BIN and PCN in the table.
      end
    end
      redirect_to email_helprx_signup_path(:u => params[:userinfo_id], :m => coupon.blank? ? "" : coupon.name, :email => email)
  end

  def send_coupon_sms
    number = params[:number]
    coupon = Coupon.find_by_id(params[:coupon_id])
    medicine = coupon.name if coupon
    discount = coupon.savings if coupon
    subsource = cookies[:hlprx_utm_subsource]
    creative = cookies[:hlprx_utm_creative]
    source_tracking3 = cookies[:hlprx_utm_source]
    source,sourcekey = generate_source(source_tracking3)
    matchtype = session[:matchtype]
    adid      = session[:adid]
    term      = session[:utm_term]
    browser   = get_browser(request.env['HTTP_USER_AGENT'].downcase)
    os        = get_operating_system(request.env['HTTP_USER_AGENT'].downcase)
    device    = get_device(request.env['HTTP_USER_AGENT'].downcase)
    searchstring = session[:searchstring]

    if !coupon.blank?
      options = {:coupon=>coupon.name,:savings=>coupon.savings.to_f,:searchstring=>searchstring,:browser=>browser,:os=>os,:device=>device,:ip=>request.env['REMOTE_ADDR'],:matchtype => matchtype,:adid => adid,:matchterm => term,:send_coupon_sms => 'true', :source=>source,:sourcekey=>sourcekey, :subsource => subsource, :creative => creative, :prescription=> medicine, :phone_number => number, :discount => discount}
      response     = get_coupon_value(options)
      @api_response = get_contact(response["Contacts"]) if response && response["Contacts"]
      cookies[:hlprx_prospect_id] = {:value => @api_response["ProspectId"], :expires => Time.now + 30.days} if @api_response && @api_response["ProspectId"]

app/views/coupons/_form.html.erb
<h4 class="admin_header">New Coupon</h4>

<%= form_for(@coupon) do |f| %>

<table align="center" class="coupons_table" cellpadding="7" cellspacing="7">
  <tr>
    <td><%= f.label :name %>:</td>
    <td><%= f.text_field :name%></td>
  </tr>
  <tr>
    <td><%= f.label :savings %>:</td>
    <td><%= f.text_field :savings%></td>
  </tr>
  <tr>
    <td><%= f.label :ailment %>:</td>
    <td><%= f.text_field :ailment%></td>
  </tr>
  <tr>
    <td><%= f.label :top_coupon  %>:</td>
    <td>  Yes: <%= f.radio_button :top_coupon, true %>
    No: <%= f.radio_button :top_coupon, false %></td>
  </tr>
  <tr>
    <td colspan="2" style="text-align: right">
     <%= f.submit 'Update', :class=>"form_buttons",:style=>"text-decoration:none" %>
      <%= link_to 'Cancel', coupons_path, :class=>"form_buttons",:style=>"text-decoration:none;padding:6px"  %>
    </td>
  </tr>
</table> 
  
<% end %>

app/views/coupons/edit.html.erb
<%= render 'form' %>

app/views/coupons/fulfillment_print.html.erb
<%= javascript_include_tag "js/jquery_1_4.js" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Helprx.info | <%= @medicine %></title>
<META NAME="keywords" CONTENT="prescriptions, drugs, rx, discounts, pharmacy, save, cheap">
<META NAME="description" CONTENT="Helprx is a directory of over 15,000 discounts that can save you money instantly at the pharmacy.">
<META HTTP-EQUIV="Content-Language" CONTENT="EN">
<META NAME="copyright" CONTENT="2009 Helprx.info All rights reserved.">
<META NAME="robots" CONTENT="FOLLOW,INDEX">
<link rel="icon" href="/assets/viewer.ico" />
<%= render :partial => 'layouts/google_analytics'%>
<style>
.left_align{
  text-align: left
}
.title{
    font-family: Arial;
    font-size: 20px;
    font-weight: bold;
    text-align: center;
}
.sub_title{
  font-family: arial;
  font-weight: bold;
  font-size: 11px;
}
#fulfill_content{
  margin-left: -24px; background-color: white; width: 107%; height: 550px; margin-top: 3px;
}
.border_none{
  border: 0;
}
</style>
</head>
<body style="background-color: #8dacd8;padding-left:15px;">
  <script src="//cdn.optimizely.com/js/31931623.js"></script>
  <div style="padding-top: 30px;text-align: right;">
    <%= image_tag "/assets/fulfillment/logo.png" %>
  </div>
  <div id="fulfill_content">
    <div style="font-weight:bold;padding-top: 50px;font-family: arial;font-size: 28px;text-align: center;">
      How would you like your coupon?
    </div>
    <div style="padding-top: 50px;width:66%;float: left">
    <table width="266" style="padding-left: 19px;">
      <tr>
        <td>
          <table cellpadding="0" cellspacing="0" width="266">
            <tr><td><img src="/assets/coupon_images/newdiscount_01.gif" width="266" height="100" alt=""/></td></tr>
            <tr>
              <td align="left" valign="top" style="padding-left:17px">
                <table cellpadding="0" cellspacing="0" style="border-left: 1px dashed;width: 248px;border-right:1px dashed">
                  <tr>
                    <td align="left" colspan="3" style="padding-left:15px;color: #2E7DBB;font-weight: bold">TAKE <br>UP TO</td>
                  </tr>
                  <tr>
                    <td valign="top" align="center"><span style="font-family:Arial, sans-serif; font-weight:bold; font-size: 35px; color: #3f7226"><%=@discount%></span> off</td>
                  </tr>
                  <tr>
                    <td colspan="3" align="center" style="padding-left:6px;color: #2E7DBB;font-size: 13px;font-weight: bold;font-family: sans-serif;">YOUR NEXT PRESCRIPTION FOR</td>
                  </tr>
                </table>
              </td>
            </tr>
            <tr>
              <td colspan="3" align="center">
                <div style="margin-left: 17px;margin-right: 53px;border-left: 1px dashed;border-right: 1px dashed;width: 246px;">
                  <span style="font-family:Verdana, Geneva, sans-serif; font-weight:bold; font-size: 17px;"><%=@medicine[0..18]%></span>
                </div>                
              </td>
            </tr>
            <tr>
              <td align="left" valign="top">
                <div style="border-left: 1px dashed; float: left; border-right: 1px dashed; width: 246px; margin-left: 17px;">
                  <img width="100px" height="70px" style="z-index: 3; margin-top: 10px; margin-left: -242px;" src="/assets/coupon_images/print_coupon_base.jpg" alt="Print_coupon_base"></img>
                  <div style="position: absolute; z-index: 4; float: left;  margin-left: 45px; margin-top: -53px;">
                    <table cellpadding="1" cellspacing="0" width="68">
                      <tbody>
                        <tr>
                          <td></td>
                          <td><span style="font-family:Arial, Helvetica, sans-serif; font-size:8px;font-weight:bold;"><%=@api_response.blank? ? $BIN : @api_response["BIN"]%></span></td>
                        </tr>
                        <tr>
                          <td></td>
                          <td><span style="font-family:Arial, Helvetica, sans-serif; font-size:8px;font-weight:bold;"><%=@api_response.blank? ? nil : @api_response["GroupNumber"]%></span></td>
                        </tr>
                        <tr>
                          <td></td>
                          <td><span style="font-family:Arial, Helvetica, sans-serif; font-size:8px;font-weight:bold;"><%=@api_response.blank? ? $PCN : @api_response["PCN"].upcase%></span></td>
                        </tr>
                        <tr>
                          <td></td>
                          <td><span style="font-family:Arial, Helvetica, sans-serif; font-size:8px;font-weight:bold;"><%=@api_response["MemberNumber"] %></span></td>
                        </tr>
                      </tbody></table>
                  </div>
                    <div style="float:left;margin-left: 110px;margin-top: 10px;width: 137px">
                      <table cellpadding="0" cellspacing="0" style="100%">
                                  <tr><td width="100px" style="font-family:Arial, Helvetica, sans-serif;font-size:7px;">PRESENT THIS AT TIME OF PURCHASE</td></tr>
                                  <tr rowspan="4"><td height="5"></td></tr>
                                </table>
                    </div>
                </div>  
              </td>
            </tr>
            <tr>
              <td>
                <div style="padding-left:3px;font-family:Arial, Helvetica, sans-serif;font-size:9px;margin-left: 17px;width: 243px;border-left: 1px dashed;border-right: 1px dashed;border-bottom: 1px dashed;">

                </div>
              </td>
            </tr>            
          </table>
        </td>
      </tr>      
    </table>
    </div>
    <div style="width:33%;float: left;margin-top: 50px">
      <table>
        <tr>
          <td>
            <%= link_to image_tag("/assets/fulfillment/PRINT_Button.png", :class=>"border_none"), "#",:onclick=>"parent.$.colorbox.close();newWindow = window.open('#{print_coupon_printable_discount_path(@coupon)}','couponPrint','height=900, width=710,menubar=no,scrollbars=no,top=100'); newWindow.focus();" %>
            <br/><span class="sub_title">Print coupons at home</span>
          </td>
        </tr>
        <tr><td>&nbsp;</td></tr>
        <tr>
          <td>
            <%= link_to image_tag("/assets/fulfillment/SMS_Button.png", :class=>"border_none"), sms_coupon_printable_discount_path(@coupon), :class=>"fancybox" %>
            <br/><span class="sub_title">Send coupons to your phone</span>
          </td>
        </tr>
        <tr><td>&nbsp;</td></tr>
        <tr>
          <td>
            <%= link_to image_tag("/assets/fulfillment/EMAIL_Button.png", :class=>"border_none"), email_coupon_printable_discount_path(@coupon), :class=>"fancybox" %>
            <br/><span class="sub_title">Receive coupons by email</span>
          </td>
        </tr>
      </table>
    </div>
  </div>
</body>
  <script type="text/javascript">
	        $(document).ready(function() {
                   if (!$.fn.colorbox) return;
                      $(".fancybox").colorbox({
                      "iframe": true,
                      "fastIframe": false,
                      "innerWidth": 510,
                      "innerHeight": 694,
                      "opacity": 0.8,
                      "scrolling": false,
                      "onComplete": function() {
                        var iframe = $("iframe.cboxIframe"),
                        body = iframe.contents().find("body"),
                        floatStyle = body.css("float");
                        body.css("float", "left");
                        $.colorbox.resize({ "innerHeight": iframe.contents().height() })
                        body.css("float", floatStyle);
                       }
                      });
                });


 </script>
</html>

app/views/coupons/index.html.erb
<h4 class="admin_header">Coupons</h4>
<style> 
  .pagination{
    text-align: center
}
</style>
<div style="margin-right:100px">
  <table align="right">
    <tr>
      <td><%= link_to 'New Coupon', new_coupon_path, :class=>"new_coupon_button", :style=>"text-decoration: none;"%></td>
      <form action="/admin/coupons/search" method='post'>
      <td>
         <input name="search" type="text" />
      </td>
      <td>
        <input type="submit" value="Search" />
      </td>
      </form>
    </tr>
  </table>
</div>
  <br/>
  <div>
<%= form_tag(coupons_path,:method=>:get, :name=>'coupons_frm') do |f| -%>
<table align="center" class="admin_tables" style=" margin-top: 20px;">
  <thead>
  <tr>
    <th>Name</th>
    <th>Savings</th>
    <th>Ailment</th>
    <th>Top Coupon</th>
    <th colspan="3">Actions</th>
  </tr>
  <tr>
    <td></td><td></td><td></td>
    <td>
       <% @search ? @top_coupon = @search[:top_coupon] : @top_coupon = "" -%>      
      <%= select_tag('search[top_coupon]', options_for_select([["All",""], ["True", "1"],["False", "0"]],@top_coupon), :onchange => "this.form.submit();") %>
    </td>
    <td colspan="2"></td>
  </tr>
  </thead>

<% @coupons.each do |coupon| %>
  <tr>
    <td><%=h coupon.name %></td>
    <td><%=h coupon.savings %></td>
    <td><%=h coupon.ailment %></td>
    <td><%=h coupon.top_coupon %></td>
    <td><%= link_to 'Edit', edit_coupon_path(coupon) %></td>
    <td><%= link_to 'Destroy', coupon, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
  </div>
<% end %>

<br />

<%= will_paginate @coupons%>

app/views/coupons/new.html.erb
<%= render 'form' %>

app/views/coupons/pdf_download.html.erb
<hr style="width:620px">
<div id="coupon_content" style="margin-left: 26px; width: 92%;">
  <div style="font-family: arial;">
    <div style="font-size: 15px; font-weight: bold; ">
      More Information: <%=@content.name%>
    </div>
    <br/><br/>
    <div>
      Important information Read this medicine information sheet carefully each time you get this medicine filled.
    </div>
    <br/><br/>
    <div>
      Issue Date: <%=@content.issue_date%>
      <br/>
      Pronunciation: <%=@content.pronunciation%>
      <br/>
      Brand Name: <%=@content.brand_name%>
      <br/><br/>
      <span style="font-weight:bold;">This medicine is used for:<%=@content.usage%></span>
    </div>
  </div>
</div>

app/views/coupons/show.html.erb
<table align="center" class="admin_tables" cellpadding="2" cellspecing="2">
    <th>Id</th>
    <th>Name</th>
    <th>Savings</th>
    <th>Ailment</th>
    <th>Top Coupon</th>
    <tr>
      <td><%=h @coupon.id %></td>

      <td><%=h @coupon.name %></td>
    
      <td><%=h @coupon.savings %></td>
    
      <td><%=h @coupon.ailment %></td>
    
      <td><%=h @coupon.top_coupon %></td>
    </tr>
    <br/>
</table>

<div align="center" style="margin-top:10px;">
<%= link_to 'Edit', edit_coupon_path(@coupon), :class=>"form_buttons",:style=>"text-decoration:none;padding:5px" %> |
<%= link_to 'Back', coupons_path, :class=>"form_buttons",:style=>"text-decoration:none;padding:6px"  %>
</div>